### ISSUE TITLE
upcoming sf breaks jpndistrict on CRAN

### ISSUE THREAD

**Issue by edzer** [uribo/jpndistrict#30]
See 
* https://www.r-spatial.org/r/2020/03/17/wkt.html
* https://win-builder.r-project.org/incoming_pretest/sf_0.9-0_20200319_213604/reverseDependencies/summary.txt

the representation of `crs` objects in sf is going to change; your tests are too strict and will break once this change takes place. New sf is in the process of submission to CRAN.

**Comment by uribo** [comment]
Thanks for announcing.

I made the fix in the local test.
I will also submit this package after the sf 0.9.0 is released.

**Comment by edzer** [comment]
Thanks, @uribo !
